#
# use this as a templete in your own config
#

##############################################################
# Template/Example for Bootstrap 3
##############################################################

#---
#Name: elementalcalltoaction
#After: 'elemental-call-to-action'
#---
#Derralf\Elements\CallToAction\Element\ElementCallToAction:
#  ## disable StyledTitle
#  title_tag_variants: null
#  title_alignment_variants: null
#  ## default/example config
#  styles:
#    DefaultWell: 'with well'
#    FullWidthWell: 'with well and full width (Container-Breakout)'
#  styles_default_description: ''
#  colors:
#    primary: 'primary'
#    success: 'success'
#    info: 'info'
#    warning: 'warning'
#    danger: 'danger'
#    myOwnCta: 'some other css-selector'
#  readmore_link_class: 'btn btn-default btn-readmore'



##############################################################
# Template/Example for Bootstrap 4
##############################################################

#---
#Name: elementalcalltoaction
#After: 'elemental-call-to-action'
#---
#
#Derralf\Elements\CallToAction\Element\ElementCallToAction:
#  ## disable StyledTitle
#  title_tag_variants: null
#  title_alignment_variants: null
#  ## Bootstrap 4 default/example config
#  styles:
#    BS4Card: 'with well (BS4-card)'
#    BS4FullWidthCard: 'with well (BS4-card) and full width (Container-Breakout)'
#  styles_default_description: ''
#  colors:
#    bg-primary: 'primary'
#    bg-secondary: 'secondary'
#    bg-light: 'light'
#    bg-success: 'success'
#    bg-danger: 'danger'
#    bg-warning: 'warning'
#    bg-info: 'info'
#    bg-dark: 'dark'
#  readmore_link_class: 'btn btn-primary btn-readmore'



